[package]
name = "timer_macro"
version = "1.0.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = "0.20.9"
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = { version = "2.0.69", features = ["full"] }
